name: vopy
channels:
- conda-forge
- pytorch
- gpytorch
dependencies:
- python>=3.10
- botorch>=0.10.0,<0.12.0
- cvxpy
- scikit-learn
- scipy
- matplotlib
- pre-commit
- pytest
- pytest-cov
- bandit
- black
- usort
- flake8
- flake8-print
- jupyter
- pydocstyle
- pip:
    - -r docs/requirements.txt
