name: torch
channels:
- conda-forge
- pytorch
- gpytorch
- nvidia
- gurobi
- mosek
dependencies:
- python=3.10
- pytorch=2.0.1
- pytorch-cuda=11.7
- gpytorch=1.11.0
- botorch=0.10.0
- pymoo=0.5.0
- cvxpy
- scikit-learn
- scipy
- oyaml
- gpy
- jupyter
- matplotlib
- numpy
- pandas
- seaborn
- jupyter
- gurobi
- mosek
- pytest
- pytest-cov
